# Site settings
title: Novies i Festa
email: your-email@domain.com
baseurl: "/noviesifesta" # the subpath of your site, e.g. /blog/
url: "http://noviesifesta.com" # the base hostname & protocol for your site
author:
  name: Olga Ferreres

# Build settings
markdown: kramdown
